title: Muhammad Mujtaba
description: Personal portfolio and academic journey of Muhammad Mujtaba, a Computer Engineering student.
url: "https://muhamamd-mujtaba.github.io"
baseurl: ""
markdown: kramdown
permalink: pretty
timezone: Asia/Karachi

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: default
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post

